name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod

      - name: Install gh-pages-cli
        run:  npm i angular-cli-ghpages --save-dev

      - name: Build deploy
        run: ng build --base-href="https://marcosferreira17.github.io/angular-teste/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ANGULARTOKEN }}
          publish_dir: ./dist/teste
          publish_branch: gh-pages


      # - name: Run gh-pages
      #   run: npx angular-cli-ghpages --dir=dist/teste

