name: Build and Deploy Angular
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Angular Full CI
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        testcommand: run test:ci
        mocha: true
