name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ng build --prod --base-href /repo-angular
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: main
          folder: dist/teste
          clean: true
