name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: npm install && npm run gh-build && cp ./dist/angular-teste/index.html ./

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ANGULARTOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./dist/angular-teste # The folder the action should deploy.
